## Load packages
library(ComplexHeatmap)
library(corrplot)
library(cowplot)
library(dplyr)
library(ggplot2)
library(pheatmap)
library(RColorBrewer)
library(tidyr)
library(tidyverse)
library(vegan)

## Correlation plot

corr <- corrplot(cor(assay(rld)), cl.lim = c(0.95,1), is.corr = F, tl.col = "black", tl.cex = 1.6,
col = colorRampPalette(c("#0099FF","ivory","#FF0090"))(200))

## Distance matrix
sampleDists <- dist(t(assay(rld)))
sampleDistMatrix <- as.matrix(sampleDists)
rownames(sampleDistMatrix) <- colnames(counts)
colnames(sampleDistMatrix) <- colnames(counts)
colors <- colorRampPalette( rev(brewer.pal(9, "Blues")) )(255)
dm <- pheatmap(sampleDistMatrix,
          clustering_distance_rows=sampleDists,
          clustering_distance_cols=sampleDists,
          col=colors, fontsize = 16)

## PCA plot
pcaData <- plotPCA(rld, intgroup=c("condition"), returnData=TRUE)
percentVar <- round(100 * attr(pcaData, "percentVar"))
pca_plot <- ggplot(pcaData, aes(PC1, PC2, color = condition, label = rownames(pcaData))) +
  geom_point(size = 3) +
  xlab(paste0("PC1: ", percentVar[1], "% variance")) +
  ylab(paste0("PC2: ", percentVar[2], "% variance")) +
  coord_fixed()
pca_plot <- pca_plot + scale_color_manual(values = c("#0099FF", "#FF0090"))
pca_plot <- pca_plot + 
  stat_ellipse(aes(group = condition, color = condition), type = "norm", level = 0.95,
               linetype = "dashed", fill = NA)
pca_plot <- pca_plot + geom_text_repel(
     aes(label = colnames(counts)),
     nudge_x = 0.1,
     nudge_y = 0.1,
     segment.size = 0.2,
     box.padding = 0.5,
     max.overlaps = Inf) 
pca_plot

## Volcano plot
SigGenesLvV <- as.data.frame(res) %>%
     rownames_to_column("GeneID")  %>%
     rename(logFC=log2FoldChange, FDR=padj)
filtTab <- SigGenesLvV %>% 
          filter(!is.na(FDR)) %>% 
          mutate(`-log10(FDR)` = -log10(FDR))
custom_colors <- c("Positive" = "#C21807", "Negative" = "#2823bc", "Non-significant" = "grey")
VP <- ggplot(filtTab, aes(x = logFC, y = `-log10(FDR)`)) + 
  geom_point(aes(colour = factor(ifelse(FDR > 0.05 | abs(logFC) < 1, "Non-significant", ifelse(logFC > 0, "Positive", "Negative")))), size = 2) +
  scale_x_continuous(limits = c(-5, 5)) +
  scale_y_continuous(limits = c(0, 25)) +
  scale_colour_manual(values = custom_colors) +
  labs(colour = "FDR Category") +
  theme(legend.position = "top") +
  geom_vline(xintercept = c(-1, 1), linetype = "dashed", color = "darkred", linewidth = 1) +
  geom_hline(yintercept = -log10(0.05), linetype = "dashed", color = "darkblue", linewidth = 1)

VP

## Plot combination

png("corrplot.png", width = 800, height = 800)
corrplot(cor(assay(rld)), cl.lim = c(0.95, 1), is.corr = FALSE, 
         tl.col = "black", tl.cex = 2.6, cl.cex = 2.4, col = colorRampPalette(c("#0099FF", "ivory", "#FF0090"))(200))
dev.off()

corr_img <- png::readPNG("corrplot.png")
corr_grob <- rasterGrob(corr_img, interpolate = TRUE)

dm_plot <- ggplotify::as.ggplot(dm$gtable)

pca_plot_labeled <- ggdraw() +
  draw_plot(pca_plot) +
  draw_label("A", x = 0, y = 1, hjust = -0.1, vjust = 1.5, size = 12, fontface = 'bold')

corr_plot_labeled <- ggdraw() +
  draw_plot(cowplot::ggdraw() + cowplot::draw_grob(corr_grob)) +
  draw_label("B", x = 0, y = 1, hjust = -0.1, vjust = 1.5, size = 12, fontface = 'bold')

dm_plot_labeled <- ggdraw() +
  draw_plot(dm_plot) +
  draw_label("C", x = 0, y = 1, hjust = -0.1, vjust = 1.5, size = 12, fontface = 'bold')

right_combined <- cowplot::plot_grid(corr_plot_labeled, dm_plot_labeled, ncol = 1, rel_heights = c(2, 2))

final_plot <- cowplot::plot_grid(pca_plot_labeled, right_combined, ncol = 2, rel_widths = c(2, 1))


final_plot


