## Pheatmaps of coocurrence matrix for WGCNA modules and cell atlas clusters

## Load packages
library(circlize)
library(ComplexHeatmap)
library(cowplot)
library(grid)

## Create color association vectors
celltype2colors <- c(
    "i-cells, early and mixed progenitors" = "#ff6666",
    "sperm and spermatogenesis" = "#66cccc",
    "neurones" = "#3366cc",
    "nematoblasts and nematocytes" = "#660099",
    "Conodipine + cells" = "#ff99cc",
    "digestive gland cells" = "#99cc66",
    "mucosal gland cells" = "#99ccff",
    "epithelial" = "#ffcc99",
    "epitheliomuscular" = "#cc0000",
    "Shematrin-like+ cells" = "#ff9900",
    "unannotated" = "#999999"
)

cellsubtype2colors <- c(
  "prog_i-cell" = "#cc3333",
  "prog_early" = "#ff6666",
  "prog_mixed" = "#ff9999",
  "gmt_1" = "#339999",
  "gmt_2" = "#66cccc",
  "ne_Rf/Glw+" = "#003366",
  "ne_Inv+" = "#3366cc",
  "ne_Fax+" = "#6699ff",
  "ne_Pkdrej+" = "#99ccff",
  "ne_4" = "#cce6ff",
  "nc_Tchh1+" = "#5e3fbd",
  "nb_1" = "#9370DB",
  "nc_Tchh2+" = "#b6a4de",
  "nb_Hrnr+" = "#d8c8eb",
  "nb_3" = "#ede4f7",
  "Cdpi3+" = "#cc6699",
  "Cdpi1+" = "#ff99cc",
  "Cdpi2+" = "#ffcce6",
  "gl_Nas4+" = "#669933",
  "gl_Nas14+" = "#99cc66",
  "gl_Chitinase2+" = "#cce6b2",
  "gl_Rsp+" = "#6699cc",
  "gl_4" = "#99ccff",
  "ep_1" = "#cc9966",
  "ep_2" = "#ffcc99",
  "ep_4" = "#ffddbb",
  "ep_5" = "#ffebcc",
  "ep_6" = "#ffeedd",
  "ep_7" = "#fff5e6",
  "ep_8" = "#fff9f0",
  "ep_9" = "#fffaf2",
  "ep_3" = "#ffe0cc",
  "em_1" = "#990000",
  "em_2" = "#cc0000",
  "em_3" = "#ff0000",
  "em_4" = "#ff3333",
  "em_5" = "#ff6666",
  "em_Shem+" = "#ff9900",
  "N/A" = "#999999"
)

relationship2colors <- c(
  "related" = "red",
  "non significant" = "ivory",
  "unrelated" = "blue"
)

module_colors <- c(
  "grey" = "grey",
  "pink" = "pink",
  "darkorange" = "darkorange",
  "red" = "red",
  "salmon" = "salmon",
  "royalblue" = "royalblue",
  "lightcyan" = "lightcyan",
  "darkgrey" = "darkgrey",
  "midnightblue" = "midnightblue",
  "grey60" = "grey60",
  "darkred" = "darkred",
  "cyan" = "cyan",
  "green" = "green",
  "turquoise" = "turquoise",
  "tan" = "tan",
  "yellow" = "yellow",
  "lightgreen" = "lightgreen",
  "orange" = "orange",
  "darkgreen" = "darkgreen",
  "lightyellow" = "lightyellow",
  "magenta" = "magenta",
  "black" = "black",
  "darkturquoise" = "darkturquoise",
  "purple" = "purple",
  "brown" = "brown",
  "blue" = "blue",
  "greenyellow" = "greenyellow"
)

module2colors <- c(
  "grey" = "grey",
  "pink" = "pink",
  "darkorange" = "darkorange",
  "red" = "red",
  "salmon" = "salmon",
  "royalblue" = "royalblue",
  "lightcyan" = "lightcyan",
  "darkgrey" = "darkgrey",
  "midnightblue" = "midnightblue",
  "grey60" = "grey60",
  "darkred" = "darkred",
  "cyan" = "cyan",
  "green" = "green",
  "turquoise" = "turquoise",
  "tan" = "tan",
  "yellow" = "yellow",
  "lightgreen" = "lightgreen",
  "orange" = "orange",
  "darkgreen" = "darkgreen",
  "lightyellow" = "lightyellow",
  "magenta" = "magenta",
  "black" = "black",
  "darkturquoise" = "darkturquoise",
  "purple" = "purple",
  "brown" = "brown",
  "blue" = "blue",
  "greenyellow" = "greenyellow"
)

##  Create missing dataframes
module_relationship <- c(rep("related", 4),
                         rep("non significant", 20),
                         rep("unrelated", 3))
relationship_colors <- c(rep("red", 4),
                         rep("ivory", 20),
                         rep("blue", 3))
modules_names <- c("green", "turquoise", "cyan", "yellow", "lightyellow", "lightcyan", "tan", "lightgreen", "orange", "salmon", "darkorange", "red", "darkred", "royalblue", "darkturquoise", "darkgreen", "purple", "magenta", "greenyellow", "grey60", "darkgrey", "grey", "midnightblue", "black", "blue", "pink", "brown")

module_classification <- data.frame(modules_names = modules_names, module_relationship = module_relationship)
cell_classification <- cell_classification[match(cluster2cells$cell_cluster, cell_classification$cell_cluster), ]
rownames(cell_classification) = NULL

## Associate vectors to data frames
cluster2celltype_colors <- celltype2colors[cell_classification$cell_type]
cluster2cellsubtype_colors <- cellsubtype2colors[cell_classification$cell_subtype]

module2relationship_colors <- relationship2colors[module_classification$module_relationship]
module2colors_colors <- module2colors[module_classification$modules_names]

## Generate simple annotations
row_anno <- rowAnnotation(
  CellType = anno_simple(cell_classification$cell_type, col = cluster2celltype_colors),
  CellSubtype = anno_simple(cell_classification$cell_subtype, col = cluster2cellsubtype_colors)
)

col_anno <- columnAnnotation(
  Relationship = anno_simple(module_classification$module_relationship, col = module2relationship_colors),
  Module = anno_simple(module_classification$modules_names, col = module2colors_colors)
)

## Create custom legends
cell_type_legend <- Legend(
  labels = names(celltype2colors), 
  legend_gp = gpar(fill = celltype2colors),  
  title = "Cell Type"
)

cell_subtype_legend <- Legend(
  labels = names(cellsubtype2colors),
  legend_gp = gpar(fill = cellsubtype2colors),  
  title = "Cell Subtype"
)

module_relationship_legend <- Legend(
  labels = names(relationship2colors), 
  legend_gp = gpar(fill = relationship2colors),  
  title = "Module Relationship"
)

l_scale_legend <- Legend(
  col_fun = colorRamp2(c(0, 30), c("white", "#B57EDC")),
  title = "Shared Genes",
   at = c(0, 10, 20, 30),
  labels = c("0", "10", "20", "30")
)

w_scale_legend <- Legend(
  col_fun = colorRamp2(c(0, 1000), c("white", "#B57EDC")),
  title = "Shared Genes",
   at = c(0, 250, 500, 750, 1000),
  labels = c("0", "250", "500", "750", "1000")
)

## Merge legends
vertical_legends <- packLegend(
  module_relationship_legend,
  cell_type_legend,
  direction = "vertical",  
  row_gap = unit(5, "mm")  
)

atlnet_legends <- packLegend(
  cell_subtype_legend,
  vertical_legends,
  direction = "horizontal", 
  column_gap = unit(5, "mm")  
)

combined_legends_leiden <- packLegend(
  l_scale_legend,
  atlnet_legends,
  direction = "vertical",  
  row_gap = unit(5, "mm")  
)

combined_legends_wilcoxon <- packLegend(
  w_scale_legend,
  atlnet_legends,
  direction = "vertical",  
  row_gap = unit(5, "mm")  
)

## Heatmaps
lhm <- Heatmap(modules_leiden_matrix, name = "Shared Genes", 
        col = colorRamp2(c(0, max(modules_leiden_matrix)), c("white", "#B57EDC")),
        cluster_rows = FALSE, cluster_columns = FALSE,
        left_annotation = row_anno,  
        top_annotation = col_anno,    
        show_row_names = FALSE,       
        show_column_names = FALSE,
        show_heatmap_legend = FALSE
)

slhm <- draw(lhm, annotation_legend_list = combined_legends_leiden)

whm <- Heatmap(modules_wilcoxon_matrix, name = "Shared Genes", 
        col = colorRamp2(c(0, max(modules_wilcoxon_matrix)), c("white", "#B57EDC")),
        cluster_rows = FALSE, cluster_columns = FALSE,
        left_annotation = row_anno,  
        top_annotation = col_anno,    
        show_row_names = FALSE,       
        show_column_names = FALSE,
        show_heatmap_legend = FALSE
)

swhm <- draw(whm, annotation_legend_list = combined_legends_wilcoxon)

## Merge
slhm_grob <- grid.grabExpr(draw(slhm))  
swhm_grob <- grid.grabExpr(draw(swhm)) 

slhm_lab <- ggdraw() +
  draw_grob(slhm_grob) +
  draw_label("A", x = 0, y = 1, hjust = -0.1, vjust = 1.5, size = 12, fontface = 'bold')

swhm_lab <- ggdraw() +
  draw_grob(swhm_grob) +
  draw_label("B", x = 0, y = 1, hjust = -0.1, vjust = 1.5, size = 12, fontface = 'bold')

combined_plot_hm <- plot_grid(slhm_lab, swhm_lab, ncol = 2, rel_widths = c(1, 1))



