## Divergence plot of expresion levens of present cell markers in DEG's assigned to each cell type known of Hydractinia

## Load packages
library(ggplo2)
library(reshape2)

## Define color palette
cell_colors  <- c("prog_i-cell" = "#cc3333", "prog_early" = "#ff6666", "prog_mixed" = "#ff9999", "gmt_1" = "#339999", "gmt_2" = "#66cccc", "ne_Rf/Glw+" = "#003366", "ne_Inv+" = "#3366cc", "ne_Fax+" = "#6699ff", "ne_Pkdrej+" = "#99ccff", "ne_4" = "#cce6ff", "nc_Tchh1+" = "#5e3fbd", "nb_1" = "#9370DB", "nc_Tchh2+" = "#b6a4de", "nb_Hrnr+" = "#d8c8eb", "nb_3" = "#ede4f7", "Cdpi3+" = "#cc6699", "Cdpi1+" = "#ff99cc", "Cdpi2+" = "#ffcce6", "gl_Nas4+" = "#669933", "gl_Nas14+" = "#99cc66", "gl_Chitinase2+" = "#cce6b2", "gl_Rsp+" = "#6699cc", "gl_4" = "#99ccff", "ep_1" = "#cc9966", "ep_2" = "#ffcc99", "ep_4" = "#ffddbb", "ep_5" = "#ffebcc", "ep_6" = "#ffeedd", "ep_7" = "#fff5e6", "ep_8" = "#fff9f0", "ep_9" = "#fffaf2", "ep_3" = "#ffe0cc", "em_1" = "#990000", "em_2" = "#cc0000", "em_3" = "#ff0000", "em_4" = "#ff3333", "em_5" = "#ff6666","em_Shem+" = "#ff9900", "N/A" = "#999999")
cell_subtype_colors <- stack(cell_colors)
colnames(cell_subtype_colors) <- c("color", "cell_subtype")

## Transform data ffrom lists to data frames
plot_data_leiden <- do.call(rbind, lapply(names(classified_cell_types_leiden), function(cell_type) {
  do.call(rbind, lapply(names(classified_cell_types_leiden[[cell_type]]), function(cell_subtype) {
    do.call(rbind, lapply(names(classified_cell_types_leiden[[cell_type]][[cell_subtype]]), function(cell_cluster) {
      df <- classified_cell_types_leiden[[cell_type]][[cell_subtype]][[cell_cluster]]
      data.frame(
        cell_type = cell_type,
        cell_subtype = cell_subtype,
        cell_cluster = cell_cluster,
        positive_genes = sum(df$LFC > 0),
        negative_genes = sum(df$LFC < 0)
      )
    }))
  }))
}))

plot_data_wilcoxon <- do.call(rbind, lapply(names(classified_cell_types_wilcoxon), function(cell_type) {
  do.call(rbind, lapply(names(classified_cell_types_wilcoxon[[cell_type]]), function(cell_subtype) {
    do.call(rbind, lapply(names(classified_cell_types_wilcoxon[[cell_type]][[cell_subtype]]), function(cell_cluster) {
      df <- classified_cell_types_wilcoxon[[cell_type]][[cell_subtype]][[cell_cluster]]
      data.frame(
        cell_type = cell_type,
        cell_subtype = cell_subtype,
        cell_cluster = cell_cluster,
        positive_genes = sum(df$LFC > 0),
        negative_genes = sum(df$LFC < 0)
      )
    }))
  }))
}))

## Reshape the data to plot
plot_data_melt_leiden <- reshape2::melt(plot_data_leiden, id.vars = c("cell_type", "cell_subtype", "cell_cluster"),
                                 variable.name = "LFC_type", value.name = "gene_count")
plot_data_melt_leiden$gene_count[plot_data_melt_leiden$LFC_type == "negative_genes"] <- 
  -plot_data_melt_leiden$gene_count[plot_data_melt_leiden$LFC_type == "negative_genes"]
plot_data_melt_leiden$cell_subtype <- factor(plot_data_melt_leiden$cell_subtype, levels = cell_subtype_colors$cell_subtype)


plot_data_melt_wilcoxon <- reshape2::melt(plot_data_wilcoxon, id.vars = c("cell_type", "cell_subtype", "cell_cluster"),
                                 variable.name = "LFC_type", value.name = "gene_count")
plot_data_melt_wilcoxon$gene_count[plot_data_melt_wilcoxon$LFC_type == "negative_genes"] <- 
  -plot_data_melt_wilcoxon$gene_count[plot_data_melt_wilcoxon$LFC_type == "negative_genes"]
plot_data_melt_wilcoxon$cell_subtype <- factor(plot_data_melt_wilcoxon$cell_subtype, levels = cell_subtype_colors$cell_subtype)

## Plot the divergence plots
ldp <- ggplot(plot_data_melt_leiden, aes(x = gene_count, y = cell_cluster, fill = cell_subtype)) +
  geom_bar(stat = "identity", position = "identity") +
  facet_grid(cell_type ~ ., scales = "free", space = "free") + 
  scale_fill_manual(values = setNames(cell_subtype_colors$color, cell_subtype_colors$cell_subtype)) +  
  geom_vline(xintercept = 0, color = "black", size = 0.5) +  
  theme_minimal() +
  labs(x = "Number of Genes", y = "Cell Clusters", fill = "Cell Subtype") +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        strip.text.y.right = element_blank(),  
        axis.text.y = element_text(size = 8),
        axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "right") +  
  guides(fill = guide_legend(ncol = 1)) 

wdp <- ggplot(plot_data_melt_wilcoxon, aes(x = gene_count, y = cell_cluster, fill = cell_subtype)) +
  geom_bar(stat = "identity", position = "identity") +
  facet_grid(cell_type ~ ., scales = "free", space = "free") + 
  scale_fill_manual(values = setNames(cell_subtype_colors$color, cell_subtype_colors$cell_subtype)) +  
  geom_vline(xintercept = 0, color = "black", size = 0.5) +  
  theme_minimal() +
  labs(x = "Number of Genes", y = "Cell Clusters", fill = "Cell Subtype") +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        strip.text.y.right = element_blank(),  
        axis.text.y = element_text(size = 8),
        axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "right") +  
  guides(fill = guide_legend(ncol = 1))

## Merge
ldpd <- ggdraw() +
  draw_plot(ldp) +
  draw_label("A", x = 0, y = 1, hjust = -0.1, vjust = 1.5, size = 12, fontface = 'bold')

wdpd <- ggdraw() +
  draw_plot(wdp) +
  draw_label("B", x = 0, y = 1, hjust = -0.1, vjust = 1.5, size = 12, fontface = 'bold')

combined_divergence <- plot_grid(ldpd, wdpd, ncol = 2, rel_widths = c(2, 2))
