## Network modulkes plotting in igraph to better visual identification of module relationships

## Extract module correlations
module_correlations <- cor(module_eigengenes)
print(module_correlations)

## Define threshold and creat adjacency matriz
cor_threshold <- 0.5 
adjacency_matrix <- (abs(module_correlations) > cor_threshold) * 1
diag(adjacency_matrix) <- 0

## Create the igraph object
g <- graph.adjacency(adjacency_matrix, mode = "undirected", diag = FALSE)

## Clean thenames of the modules
module_names <- colnames(module_eigengenes)
cleaned_module_names <- gsub(pattern = "ME", replacement = "", x = module_names)

## Extract the colors from the corlevelplot
correlation_color <- c("#bce3ed", "#3450f7", "#a0d8ec", "#d7eeee", "#fff9ec", "#8fd1eb", "#88ceeb", "#92d2eb",
                              "#ff9aa3", "#ffd4d6", "#ffc0cb", "#ff5f64", "#ff4b4f", "#ff5357", "#fffbed", "#ff6268",
                              "#ffc5ce", "#ffd4d6", "#ffccd2", "#ffd2d6", "#ffdddc", "#ffe5e0", "#fff7eb", "#69a1ef",
                              "#5b8cf1", "#0000ff", "#c3e6ed")

module_name <- c("greenyellow", "blue", "brown", "purple", "darkturquoise", "black", "magenta", "lightyellow", "darkgreen",
                 "orange", "lightgreen", "yellow", "tan", "turquoise", "green", "cyan","darkred", "grey60", "midnightblue",
                 "darkgrey", "lightcyan", "royalblue", "salmon", "red", "darkorange", "pink", "grey")

module_correlation_colors <- data.frame(module_name = module_name, correlation_color = correlation_color, stringsAsFactors = FALSE)

## Assing the cleaned mocule names to the network vertices
V(g)$name <- cleaned_module_names
V(g)$color <- module_correlation_colors$correlation_color[match(cleaned_module_names, module_correlation_colors$module_name)]
V(g)$label.color <- "black"

## Plot the network
layout <- layout_with_kk(g)

plot(g, layout = layout,
     vertex.size = 10,
     vertex.label.cex = 0.8,
     vertex.label.dist = -1,
     vertex.label.degree = pi/2,
     vertex.label = V(g)$name, 
     vertex.color = V(g)$color)
