## Dor plots for GSEA and EA
## Load Packages
library(clusterProfiler)
library(ggplot2)

## Draw
EA_GO_dot <- dotplot(EA_GO, showCategory = 13) + ggtitle("Enrichment Analysis GO")
EA_GO_dot

GSEA_GO_dot <- dotplot(GSEA_GO, showCategory = 11) + ggtitle("GSEA GO")
GSEA_GO_dot

EA_KEGG_dot <- dotplot(EA_KEGG, showCategory = 11) + ggtitle("Enrichment Analysis KEGG")
EA_KEGG_dot

GSEA_KEGG_dot <- dotplot(GSEA_KEGG, showCategory = 11) + ggtitle("GSEA  KEGG")
GSEA_KEGG_dot

M_KEGG_dot <- dotplot(M_KEGG, showCategory = 9) + ggtitle("GSEA  KEGG")
M_KEGG_dot

EA_GO_dot_labeled <- ggdraw() +
  draw_plot(EA_GO_dot) +
  draw_label("A", x = 0, y = 1, hjust = -0.1, vjust = 1.5, size = 12, fontface = 'bold')

GSEA_GO_dot_labeled <- ggdraw() +
  draw_plot(GSEA_GO_dot) +
  draw_label("B", x = 0, y = 1, hjust = -0.1, vjust = 1.5, size = 12, fontface = 'bold')

GO_combined_plot <- cowplot::plot_grid(EA_GO_dot_labeled, GSEA_GO_dot_labeled, ncol = 2, rel_widths = c(1, 1))

## Merge plots
EA_dot <- ggdraw() +
  draw_plot(xx_dot) +
  draw_label("A", x = 0, y = 1, hjust = -0.1, vjust = 1.5, size = 12, fontface = 'bold')

GSEA_dot <- ggdraw() +
  draw_plot(yy_dot) +
  draw_label("B", x = 0, y = 1, hjust = -0.1, vjust = 1.5, size = 12, fontface = 'bold')

combined_plot_dot <- plot_grid(EA_dot, GSEA_dot, ncol = 2, rel_widths = c(2, 2))
