## Comparisson of interesting domain containing proteins between our three selected cathegories and bar and venn plotting

## Load packages
library(circlize)
library(cowplot)
library (dplyr)
library(ggplot2)
library(ggrepel)
library(ggVennDiagram)
library(vegan)

## Unlist and comparisson

## Unlist each cathegory
matching_indices_anot <- grep(common_part, names(results_anot))
matching_objects_anot <- results_anot[matching_indices_anot]
all_terms_annot <- unlist(matching_objects_anot)
num_unique_terms_annot <- length(unique(all_terms_annot))

matching_indices_unnanot <- grep(common_part, names(results_unnanot))
matching_objects_unnanot <- results_unnanot[matching_indices_unnanot]
all_terms_unnannot <- unlist(matching_objects_unnanot)
num_unique_terms_unnannot <- length(unique(all_terms_unnannot))

matching_indices_unenriched <- grep(common_part, names(results_unenriched))
matching_objects_unenriched <- results_unenriched[matching_indices_unenriched]
all_terms_unenriched <- unlist(matching_objects_unenriched)
num_unique_terms_unenriched <- length(unique(all_terms_unenriched))

## Transform into dataframes
result_df_annot <- data.frame()

for (i in seq_along(matching_objects_anot)) {
    name <- names(matching_objects_anot)[i]
    num_terms <- length(matching_objects_anot[[i]])
    row <- data.frame(name = name, num_terms = num_terms)
    result_df_annot <- rbind(result_df_annot, row)
}

result_df_unnannot <- data.frame()

for (i in seq_along(matching_objects_unnanot)) {
    name <- names(matching_objects_unnanot)[i]
    num_terms <- length(matching_objects_unnanot[[i]])
    row <- data.frame(name = name, num_terms = num_terms)
    result_df_unnannot <- rbind(result_df_unnannot, row)
}

result_df_unenriched <- data.frame()

for (i in seq_along(matching_objects_unenriched)) {
  name <- names(matching_objects_unenriched)[i]
  num_terms <- length(matching_objects_unenriched[[i]])
  row <- data.frame(name = name, num_terms = num_terms)
  result_df_unenriched <- rbind(result_df_unenriched, row)
}

## Merge the dataframe columns
result_df_annot$name <- gsub("unique_", "", result_df_annot$name)
result_df_annot$name <- gsub("_description", "", result_df_annot$name)
result_df_annot$name <- gsub("_domain_name", "", result_df_annot$name)
sum_df_annot <- aggregate(num_terms ~ name, data = result_df_annot, sum)

result_df_unnannot$name <- gsub("unique_", "", result_df_unnannot$name)
result_df_unnannot$name <- gsub("_description", "", result_df_unnannot$name)
result_df_unnannot$name <- gsub("_domain_name", "", result_df_unnannot$name)
sum_df_unnannot <- aggregate(num_terms ~ name, data = result_df_unnannot, sum)

result_df_unenriched$name <- gsub("unique_", "", result_df_unenriched$name)
result_df_unenriched$name <- gsub("_description", "", result_df_unenriched$name)
result_df_unenriched$name <- gsub("_domain_name", "", result_df_unenriched$name)
sum_df_unenriched <- aggregate(num_terms ~ name, data = result_df_unenriched, sum)

## Merge into a unique data frame
comparisson <- merge(sum_df_annot, sum_df_unnannot, by = "name", suffixes = c("_Annotated Genes", "_Unnanotated Genes"))
comparisson <- merge(comparisson, sum_df_unenriched, by = "name", suffixes = c("", "_Unenriched"))

names(comparisson)[names(comparisson) == "num_terms_Annotated Genes"] <- "Annotated Enriched Genes"
names(comparisson)[names(comparisson) == "num_terms_Unnanotated Genes"] <- "Unannotated Genes"
names(comparisson)[names(comparisson) == "num_terms"] <- "Annotated Unenriched Genes"

## Bar plot
plot_domains <- comparisson %>%
  pivot_longer(cols = ends_with("Genes"), names_to = "Annotation", values_to = "Number of IDCP")

plot_domains_filtered <- plot_domains %>%
  filter(`Number of IDCP` != 0)

p <- ggplot(plot_domains_filtered, aes(x = name, y = `Number of IDCP`, fill = Annotation)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Comparison of Gene Annotations", x = "Domain", y = "Number of IDCP") +
  theme_minimal() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        axis.text.x = element_text(angle = 45, hjust = 1, size = 8)) +
  
scale_fill_manual(values = c("Annotated Enriched Genes" = "#F8766D",
                               "Unannotated Genes" = "#00BFC4",
                               "Annotated Unenriched Genes" = "#9590FF"))
p

## Venn plot

only_annot <- subset(sum_df_annot, num_terms != 0)
only_unnannot <- subset(sum_df_unnannot, num_terms != 0)
only_unenrich <- subset(sum_df_unenriched, num_terms != 0)

venn_annot <- only_annot$name
venn_unnannot <- only_unnannot$name
venn_unenrich <- only_unenrich$name

venn_lists <- list(E = venn_annot, UA = venn_unnannot, UE = venn_unenrich)
venn <- Venn(venn_lists)
venn_data <- process_data(venn)
venn_plot <- ggplot() +
  geom_polygon(aes(Y + 0.5, X - 1, fill = name, group = id), 
               data = venn_regionedge(venn_data),
               show.legend = FALSE) +
  geom_path(aes(Y + 0.5, X - 1, color = id, group = id), 
            data = venn_setedge(venn_data), 
            linewidth = 1,
            show.legend = FALSE) +
  geom_text(aes(Y, X - 1, label = name),
            size = 7,
            data = venn_setlabel(venn_data)) +
  geom_label(aes(Y + 0.5, X - 1, label = count),
             size = 7,
             data = venn_regionlabel(venn_data),
             alpha = 0) +
  scale_fill_manual(values = c("E" = "#F8766D", "UA" = "#00BFC4", "UE" = "#9590FF", "E/UA" = "#7c9a98", "E/UE" = "#c683b6", "UA/UE" = "#4aa7e1", "E/UA/UE" = "#8895cb")) + 
  scale_color_manual(values = c("1" = "black", "2" = "black", "3" = "black")) +
  coord_equal() +
  theme_void() 

venn_plot

## Merge plots 
p_lab <- ggdraw() +
  draw_plot(p) +
  draw_label("A", x = 0, y = 1, hjust = -0.1, vjust = 1.5, size = 12, fontface = 'bold')

venn_lab <- ggdraw() +
  draw_plot(venn_plot) +
  draw_label("B", x = 0, y = 1, hjust = -0.1, vjust = 1.5, size = 12, fontface = 'bold')

combined_plot_dom <- plot_grid(p_lab, venn_lab, ncol = 2, rel_widths = c(3, 1))
